### ISSUE TITLE
[BE-003] Raw sql table? 

### ISSUE THREAD

**Issue by gentsk77** [Susanou/EECS341-Final#4]
All existing queries are written in raw sql queries as required, tho I'm not sure how to apply raw sql create tables. 
The actual create tables are retreivable with `python manage.py sqlmigrate <seqnumber>`. The only problem is how do we use it instead of models.

**Comment by Susanou** [comment]
For this one I need to find back the email I got but there is a tag that you add to the model so that it still exists but doesn’t create tables

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
